apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "attribution.ia.cmname" . }}
  namespace: {{ .Release.Namespace }}
data:
  default_redis_config: '{"address":["9.134.67.201:7000"],"is_cluster":1}'
  key_manager_name: redis
  serverAddress: :9020
  metric_server_address: :9025
  imp_kv_type: LEVELDB
  imp_kv_address: ./db
  imp_kv_password: ''
  imp_attribution_worker_count: "50"
  imp_attribution_queue_size: "200"
  imp_attribution_queue_timeout_ms: "1000"
  ams_encrypt_url: http://localhost:9010/encrypt
  ams_decrypt_url: http://localhost:9010/decrypt
  hdfs_address: ''
  hdfs_user: ''
  v: "100"
