apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ia.name }}
  labels:
    {{- include "attribution.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ia.autoscaling.enabled }}
  replicas: {{ .Values.ia.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "attribution.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ia.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "attribution.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "attribution.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ia.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.ia.name }}
          securityContext:
            {{- toYaml .Values.ia.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{ range .Values.ia.commands }}
            - {{ . }}
            {{ end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.ia.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "attribution.ia.cmname" . }}
      {{- with .Values.ia.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ia.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ia.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
