apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "attribution.ia.fullname" . }}
  labels:
    {{- include "attribution.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ia.replicaCount }}
  selector:
    matchLabels:
      {{- include "attribution.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.metrics.enabled }}
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/scrape: "true"
        {{- end }}
        {{- if .Values.ia.podAnnotations }}
        {{- toYaml .Values.ia.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "attribution.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.enabled -}}
      serviceAccountName: {{ include "attribution.fullname" . }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.ia.securityContext | nindent 8 }}
      containers:
        - name: {{ .Values.ia.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- range .Values.ia.commands }}
            - {{ . }}
            {{- end }}
          env:
          - name: server_address
            value: ":{{ .Values.ia.service.port }}"
          {{- if .Values.metrics.enabled }}
          - name: metrics_address
            value: ":{{ .Values.metrics.port }}"
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "attribution.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.ia.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.ia.resources | nindent 12 }}
      {{- with .Values.ia.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ia.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ia.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
