{{- if .Values.ia.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "attribution.ia.fullname" . }}
  labels:
    {{- include "attribution.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "attribution.ia.fullname" . }}
  minReplicas: {{ .Values.ia.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ia.autoscaling.maxReplicas }}
  metrics:
{{ toYaml .Values.ia.autoscaling.metrics | indent 4 }}
{{- end }}
