apiVersion: v1
kind: Service
metadata:
  name: {{ include "attribution.ia.fullname" . }}
  labels:
    {{- include "attribution.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ia.service.type }}
  ports:
    - port: {{ .Values.ia.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "attribution.selectorLabels" . | nindent 4 }}
