image:
  repository: tencentad/attribution
  pullPolicy: Always
  tag: latest

imagePullSecrets: []

serviceAccount:
  enabled: false
  annotations: {}

metrics:
  enabled: true
  port: 8080

ia:
  name: imp-attribution-server
  replicaCount: 1
  
  commands:
  - imp_attribution_server

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: chart-example.local
        paths: []
    tls: []

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}


  persistentVolume:
    enabled: false
    accessModes:
      - ReadWriteOnce
    annotations: {}
    existingClaim: ""
    mountPath: /data
    size: 2Gi
    # storageClass: "-"
    # volumeBindingMode: ""
    subPath: ""

redis:
  enabled: false
