name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
        
    - name: Get dependencies
      run: |
        cd attribution
        go get honnef.co/go/tools/cmd/staticcheck
        
    - name: Build
      run: |
        cd attribution
        go install -v attribution_server.go

    - name: Test
      run: |
        cd attribution
        go test -covermode=atomic -coverpkg=./... ./... -bench . -benchmem
    
    - name: Go vet
      run: |
        cd attribution
        go vet -httpresponse -assign -nilfunc -printf -unreachable -atomic ./...
      
    - name: Staticcheck
      run: |
        cd attribution
        staticcheck ./...
